version: '3.8'

services:
  db:
    image: postgres:13
    container_name: leave-system-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: leave_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leave-network

networks:
  leave-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
